// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bach_bash.Persistence;

#nullable disable

namespace bach_bash.Migrations
{
    [DbContext(typeof(BashDbContext))]
    [Migration("20260629215720_initialCreate2")]
    partial class initialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bach_bash.Models.Bash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Bashes", "app");
                });

            modelBuilder.Entity("bach_bash.Models.BashMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BashId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasherId1")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BashId");

                    b.HasIndex("BasherId");

                    b.HasIndex("BasherId1");

                    b.ToTable("BashMembers", "app");
                });

            modelBuilder.Entity("bach_bash.Models.Basher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Bashers", "app");
                });

            modelBuilder.Entity("bach_bash.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BashId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BashId");

                    b.ToTable("Challenges", "app");
                });

            modelBuilder.Entity("bach_bash.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Place")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("BasherId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("Id");

                    b.ToTable("Submissions", "app");
                });

            modelBuilder.Entity("bach_bash.Models.BashMember", b =>
                {
                    b.HasOne("bach_bash.Models.Bash", "Bash")
                        .WithMany("BashMmebers")
                        .HasForeignKey("BasherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bach_bash.Models.Basher", "Basher")
                        .WithMany()
                        .HasForeignKey("BasherId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bash");

                    b.Navigation("Basher");
                });

            modelBuilder.Entity("bach_bash.Models.Basher", b =>
                {
                    b.HasOne("bach_bash.Models.Bash", "Bash")
                        .WithOne("Owner")
                        .HasForeignKey("bach_bash.Models.Basher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bash");
                });

            modelBuilder.Entity("bach_bash.Models.Challenge", b =>
                {
                    b.HasOne("bach_bash.Models.Bash", "Bash")
                        .WithMany("Challenges")
                        .HasForeignKey("BashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bash");
                });

            modelBuilder.Entity("bach_bash.Models.Submission", b =>
                {
                    b.HasOne("bach_bash.Models.Basher", "Basher")
                        .WithMany("Submissions")
                        .HasForeignKey("BasherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bach_bash.Models.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basher");

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("bach_bash.Models.Bash", b =>
                {
                    b.Navigation("BashMmebers");

                    b.Navigation("Challenges");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("bach_bash.Models.Basher", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("bach_bash.Models.Challenge", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
